server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: authlogs 
      __path__: /var/log/auth.log
  - targets:
      - localhost
    labels:
      job: daemonlogs 
      __path__: /var/log/daemon.log
  - targets:
      - localhost
    labels:
      job: debuglogs 
      __path__: /var/log/debug
  - targets:
      - localhost
    labels:
      job: kernellogs 
      __path__: /var/log/kern.log
  - targets:
      - localhost
    labels:
      job: systemlogs 
      __path__: /var/log/syslog
