route:
    receiver: 'slack'

receivers:
    - name: 'slack'
      slack_configs:
          - send_resolved: true
            text: "{{ .CommonAnnotations.description }}"
            username: 'Prometheus'
            channel: '#liveonit-svr-notifications'
            api_url: 'https://hooks.slack.com/services/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'
